services:
  - type: web
    name: niakvio-official-tv
    runtime: docker
    dockerfilePath: ./tv-addon/Dockerfile
    dockerContext: ./tv-addon
    healthCheckPath: /manifest.json
    autoDeploy: true
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
