#!/usr/bin/env python3
from __future__ import annotations
import importlib.util,subprocess,tempfile,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/"scripts"))
spec=importlib.util.spec_from_file_location("resolver",ROOT/"scripts/provider_patches/global_media_type_resolution_v1.py");mod=importlib.util.module_from_spec(spec);assert spec.loader;spec.loader.exec_module(mod)
BASE='''\n"use strict";\nasync function getStreams(id,type,season,episode){const c=globalThis.__nuvioMediaContext||{};return [{url:"https://media.example/ok.m3u8",receivedId:String(id),receivedType:String(type),season,episode,tmdbId:c.tmdbId||"",imdbId:c.imdbId||"",sourceId:c.sourceId||"",sourceIdType:c.sourceIdType||"",degraded:c.tmdbResolutionDegraded===true}]}\nmodule.exports={getStreams,__niakvioProviderBase:{identityInput:{mode:"catalog_search",requiresTmdbBeforeRun:true}}};\n'''
SOURCE=mod.apply(BASE,options={"semantic_types":["movie","tv"]})
def run(js):
  with tempfile.TemporaryDirectory() as td:
    d=Path(td);(d/"p.cjs").write_text(SOURCE,encoding="utf-8");(d/"t.cjs").write_text(js,encoding="utf-8");r=subprocess.run(["node",str(d/"t.cjs"),str(d/"p.cjs")],text=True,capture_output=True);assert r.returncode==0,r.stdout+r.stderr
run('''\nlet calls=0;global.__native_fetch=()=>{};global.fetch=async u=>{calls++;throw new Error("unexpected "+u)};const p=require(process.argv[2]);(async()=>{let v=await p.getStreams("tt11198330:3:1","series",3,1),x=v[0];if(!x||x.receivedId!=="tt11198330"||x.receivedType!=="tv"||x.imdbId!=="tt11198330"||x.sourceIdType!=="imdb")throw new Error(JSON.stringify(v));let y=(await p.getStreams("tmdb:94997:3:1","series",3,1))[0];if(!y||y.receivedId!=="94997"||y.tmdbId!=="94997"||y.sourceIdType!=="tmdb")throw new Error(JSON.stringify(y));if(calls!==0)throw new Error("credentialless native runtime touched TMDB "+calls)})().catch(e=>{console.error(e);process.exit(1)});\n''')
run('''\nglobal.TMDB_API_KEY="0123456789abcdef0123456789abcdef";let calls=0;global.fetch=async u=>{u=String(u);calls++;if(u.includes("/find/tt11198330"))return{ok:true,status:200,json:async()=>({movie_results:[],tv_results:[{id:94997,name:"House of the Dragon"}]})};if(u.includes("/tv/94997/season/3/episode/1"))return{ok:true,status:200,json:async()=>({id:1})};if(u.includes("/tv/94997?"))return{ok:true,status:200,json:async()=>({id:94997,name:"House of the Dragon",genres:[{id:18}],original_language:"en",external_ids:{imdb_id:"tt11198330"}})};throw new Error(u)};const p=require(process.argv[2]);(async()=>{const x=(await p.getStreams("tt11198330:3:1","series",3,1))[0];if(!x||x.receivedId!=="94997"||x.tmdbId!=="94997"||x.imdbId!=="tt11198330"||x.degraded!==false)throw new Error(JSON.stringify(x));const m=await global.__nuvioCoreGetTmdbDataV1({id:"tt11198330:3:1",mediaType:"series",season:3,episode:1});if(!m||m.state!=="ok"||m.tmdbId!=="94997"||m.imdbId!=="tt11198330")throw new Error(JSON.stringify(m))})().catch(e=>{console.error(e);process.exit(1)});\n''')
print("native dual IMDb/TMDB identity tests passed")
