#!/usr/bin/env python3
"""Align one-provider materialization with authoritative publication finalization.

The full publication path owns deterministic final stages that targeted
materialization must reproduce before publishing an asset:
1. provider security normalization after Provider/Core composition;
2. the canonical content-addressed publication filename grammar;
3. atomic replacement of the provider's materialization-ledger row.

Without these stages a domain-only rebuild can reintroduce unsafe console sinks,
create a non-canonical filename, or leave manifest and materialization identities
disagreeing even though the generated bytes are correct.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "scripts" / "materialize_provider_v3_one.py"
SECURITY_MARKER = "TARGETED_MATERIALIZER_SECURITY_FINALIZATION_V61"
NAME_MARKER = "TARGETED_MATERIALIZER_PUBLISHED_NAME_V61"
LEDGER_MARKER = "TARGETED_MATERIALIZER_LEDGER_V61"


def main() -> int:
    text = PATH.read_text(encoding="utf-8")
    changed = False

    import_anchor = "import materialize_provider_v3_all as allmat\n"
    if SECURITY_MARKER not in text:
        import_replacement = (
            import_anchor
            + "from provider_security_hardening import assert_hardened, harden_bytes\n"
        )
        if text.count(import_anchor) != 1:
            raise SystemExit("targeted materializer security import anchor missing/ambiguous")
        text = text.replace(import_anchor, import_replacement, 1)

        anchor = '''    bundle, applied = allmat.apply_overrides(
        provider_id,
        bundle,
        phase="discovery",
        include_global_core=True,
        config_path=allmat.DEFAULT_OVERRIDES,
    )
    text = bundle.decode("utf-8", errors="strict")
'''
        replacement = '''    bundle, applied = allmat.apply_overrides(
        provider_id,
        bundle,
        phase="discovery",
        include_global_core=True,
        config_path=allmat.DEFAULT_OVERRIDES,
    )

    # TARGETED_MATERIALIZER_SECURITY_FINALIZATION_V61
    # Match the authoritative publication pipeline: deterministic security
    # normalization owns the final provider bytes after Provider/Core composition.
    # This is not a post-publication mutation; it is part of composition before
    # minimizer/fixed-point validation and before the asset is written.
    bundle, security_report = harden_bytes(bundle)
    text = bundle.decode("utf-8", errors="strict")
    assert_hardened(text)
'''
        if text.count(anchor) != 1:
            raise SystemExit("targeted materializer security composition anchor missing/ambiguous")
        text = text.replace(anchor, replacement, 1)

        report_anchor = '''        "minimizer": minimizer_report,
'''
        report_replacement = '''        "minimizer": minimizer_report,
        "securityFinalization": {
            "revision": 1,
            "normalized": bool(security_report.get("changed")),
            "consoleSinkChanges": int(security_report.get("consoleSinkChanges") or 0),
            "consoleShadow": bool(security_report.get("consoleShadow")),
            "hostnameChanges": int(security_report.get("hostnameChanges") or 0),
        },
'''
        if text.count(report_anchor) != 1:
            raise SystemExit("targeted materializer security report anchor missing/ambiguous")
        text = text.replace(report_anchor, report_replacement, 1)
        changed = True

    if NAME_MARKER not in text:
        security_import = "from provider_security_hardening import assert_hardened, harden_bytes\n"
        publication_import = "from reapply_published_overrides import published_name\n"
        if publication_import not in text:
            if text.count(security_import) != 1:
                raise SystemExit("targeted materializer publication import anchor missing/ambiguous")
            text = text.replace(security_import, security_import + publication_import, 1)

        name_anchor = '''    digest = hashlib.sha256(bundle).hexdigest()
    filename = f"{provider_id}-{digest[:16]}.js"
    relative = f"providers/{filename}"
'''
        name_replacement = '''    digest = hashlib.sha256(bundle).hexdigest()
    # TARGETED_MATERIALIZER_PUBLISHED_NAME_V61
    # Reuse the authoritative finalizer grammar so fixed-point bytes also have
    # a fixed-point content-addressed reference. Never invent a second naming
    # convention in the targeted rebuild path.
    previous_relative = str(entry.get("filename") or "").strip()
    previous_path = Path(previous_relative) if previous_relative else Path(f"{provider_id}--nuvio--seed.js")
    filename = published_name(provider_id, previous_path, digest)
    relative = f"providers/{filename}"
'''
        if text.count(name_anchor) != 1:
            raise SystemExit("targeted materializer published-name anchor missing/ambiguous")
        text = text.replace(name_anchor, name_replacement, 1)
        changed = True

    if LEDGER_MARKER not in text:
        main_anchor = '''def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("provider_id")
    args = parser.parse_args()
    materialize_one(args.provider_id)
    return 0
'''
        main_replacement = '''def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("provider_id")
    args = parser.parse_args()
    report = materialize_one(args.provider_id)

    # TARGETED_MATERIALIZER_LEDGER_V61
    # materialize_one() changes the published manifest identity, therefore the
    # same transaction must replace the matching materialization row. Leaving the
    # old row behind makes provenance reconciliation observe two different assets.
    ledger = allmat.load(allmat.DEFAULT_REPORT)
    rows = [row for row in ledger.get("providers") or [] if isinstance(row, dict)]
    target = allmat.canonical_id(str(report.get("provider") or ""))
    matches = [index for index, row in enumerate(rows) if allmat.canonical_id(str(row.get("provider") or "")) == target]
    if len(matches) != 1:
        raise ValueError(f"{target}: materialization ledger row cardinality={len(matches)} expected=1")
    rows[matches[0]] = report
    ledger["providers"] = rows

    aggregate = hashlib.sha256()
    for row in rows:
        row_provider = allmat.canonical_id(str(row.get("provider") or ""))
        row_digest = str(row.get("sha256") or "").strip().casefold()
        if not row_provider or len(row_digest) != 64:
            raise ValueError(f"invalid materialization ledger row: {row_provider!r}")
        aggregate.update(row_provider.encode("utf-8"))
        aggregate.update(bytes.fromhex(row_digest))
    ledger["generation"] = aggregate.hexdigest()
    ledger["providerCount"] = len(rows)
    ledger["expectedProviderCount"] = len(rows)
    allmat.write_json(allmat.DEFAULT_REPORT, ledger)
    print(
        "FIELD_PROVIDER_V3_ONE_LEDGER "
        f"provider={target} file={report.get('file')} sha256={str(report.get('sha256') or '')[:16]} "
        f"generation={ledger['generation'][:16]}"
    )
    return 0
'''
        if text.count(main_anchor) != 1:
            raise SystemExit("targeted materializer ledger main anchor missing/ambiguous")
        text = text.replace(main_anchor, main_replacement, 1)
        changed = True

    PATH.write_text(text, encoding="utf-8")
    print(
        "V61_TARGETED_PUBLICATION_PATCH "
        f"changed={str(changed).lower()} security={str(SECURITY_MARKER in text).lower()} "
        f"canonical_name={str(NAME_MARKER in text).lower()} ledger={str(LEDGER_MARKER in text).lower()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
