#!/usr/bin/env python3
"""Validate/persist declared-hub activation publication state.

This helper never discovers hubs and never repairs providers. It only projects the
explicit provider-overrides.json `official_hub` authority into a durable scope,
verifies the rendered catalogue, and appends a recovery checkpoint when asked.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPECTED = 96


def load(rel: str):
    return json.loads((ROOT / rel).read_text(encoding="utf-8"))


def cid(value: object) -> str:
    return str(value or "").strip().casefold().replace("_", "-")


def compute_scope() -> dict:
    manifest = load("manifest.json")
    overrides = load("provider-overrides.json")
    patches = overrides.get("provider_patches") if isinstance(overrides.get("provider_patches"), dict) else {}
    rows = [row for row in manifest.get("scrapers") or [] if isinstance(row, dict)]
    assert len(rows) == EXPECTED, len(rows)
    enabled, disabled = [], []
    for row in rows:
        pid = cid(row.get("id"))
        patch = patches.get(pid) if isinstance(patches.get(pid), dict) else {}
        hub = str(patch.get("official_hub") or "").strip()
        expected = bool(hub)
        assert bool(row.get("enabled")) is expected, (pid, row.get("enabled"), hub)
        mo = patch.get("manifest_overrides") if isinstance(patch.get("manifest_overrides"), dict) else {}
        assert bool(mo.get("enabled")) is expected, (pid, mo.get("enabled"), hub)
        (enabled if expected else disabled).append(pid)
    assert enabled and len(enabled) < EXPECTED
    return {
        "schemaVersion": 1,
        "authority": "provider-overrides.json:provider_patches.*.official_hub",
        "catalogueProviderCount": EXPECTED,
        "enabledProviderCount": len(enabled),
        "disabledProviderCount": len(disabled),
        "enabledProviders": sorted(enabled),
        "disabledProviders": sorted(disabled),
        "repairScope": "declared-hub-providers-only",
        "nativeLabPolicy": "reuse-existing-artifacts-first; rerun-only-for-specific-fix-validation",
    }


def write_scope(scope: dict) -> None:
    target = ROOT / "automation/hub-activation-scope.json"
    target.write_text(json.dumps(scope, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def verify_catalog(scope: dict) -> None:
    catalog = load("provider_catalog.json")
    overrides = load("provider-overrides.json")
    patches = overrides.get("provider_patches") if isinstance(overrides.get("provider_patches"), dict) else {}
    actual = []
    providers = catalog.get("providers") or []
    assert len(providers) == EXPECTED, len(providers)
    for row in providers:
        scraper = row.get("scraper") or {}
        pid = cid(row.get("canonicalId") or scraper.get("id"))
        patch = patches.get(pid) if isinstance(patches.get(pid), dict) else {}
        hub = str(patch.get("official_hub") or "").strip()
        assert bool(scraper.get("enabled")) == bool(hub), (pid, scraper.get("enabled"), hub)
        if scraper.get("enabled"):
            actual.append(pid)
    assert sorted(actual) == sorted(scope["enabledProviders"]), (actual, scope["enabledProviders"])


def append_memory(scope: dict) -> None:
    memory = ROOT / "MEMORY.md"
    text = memory.read_text(encoding="utf-8")
    marker = "## 2026-09-11 — declared-hub activation + artifact-first repair checkpoint"
    if marker in text:
        return
    version = str(load("manifest.json").get("version") or "unknown")
    block = f'''\n\n{marker}\n\nThis checkpoint supersedes the short-lived force-all-96 activation policy.\n\n### Publication / activation authority\n- Catalogue census remains 96 Provider Objects for recovery/history; catalogue membership is not activation.\n- **Single activation rule:** enabled iff `provider-overrides.json -> provider_patches.<provider>.official_hub` is non-empty.\n- Publication generated by this transaction: **{version}**.\n- Declared-hub enabled providers: **{scope["enabledProviderCount"]}**; hub-less disabled providers: **{scope["disabledProviderCount"]}**.\n- `on / repair / off` remains route/DATA diagnostic evidence only and never overrides hub activation.\n- Durable scope: `automation/hub-activation-scope.json`.\n\n### Native Lab / repair operating rule\n- Repair scope is **declared-hub providers only** until explicitly changed.\n- Reuse existing native OS Lab artifacts/logs first; do **not** rerun all Labs systematically.\n- Rerun only the affected OS/provider/fixture to validate a concrete repair or when exact evidence is absent/stale.\n- Failure classes: not executed / no provider network / zero streams / wrong content / duplicate streams / invalid transport / player-client failure.\n- A URL or HTTP 206 is not success: stream acceptance requires requested work/episode identity, useful non-duplicate output and media integrity.\n\n### Allwish — high-priority integrity regression\n- User confirms Allwish still returns two identical/unrelated streams.\n- Existing 5.21.42 native artifacts corroborate it: Interstellar and Breaking Bad S01E01 both yield two Allwish rows with generic `All-Wish #2` and host `cdn4.telesco.pe`, while the old Lab marked extraction healthy because media bytes existed.\n- Allwish is therefore **wrong-content + duplicate/fixture-invariant**, not green, unless/until identity is independently proven and corrected.\n\n### Active repair plan\n1. Build provider × OS × fixture evidence matrix from existing Android/iOS/macOS/Windows/TV artifacts, filtered to declared-hub scope.\n2. Prioritize wrong-content/duplicate, then not-executed/no-network, then zero-stream, then transport/player integrity.\n3. If Allwish is hub-enabled, repair it first and add a cross-fixture identity regression; if hub-less, keep it disabled and retain the defect as evidence.\n4. Repair hub providers only from observed artifact evidence; preserve shared Core ownership and provider-specific DATA evidence.\n5. Validate with the smallest static/local/provider test; native rerun only when the affected repair needs native confirmation.\n6. Domain Refresh may change activation only by changing final declared `official_hub`; route proof does not own activation.\n7. Update the evidence matrix and this MEMORY checkpoint after accepted repairs/publications.\n\n### Deferred backlog not to lose\n- Make native harness truth truthful: wrong-content/duplicates cannot be `extractionHealthy`; separate player-client failures from provider failures.\n- TV Android: current NuvioTV HEAD has upstream `topInputFocusRequester` compile regression; use audited ref only for targeted validation.\n- Ingest current iOS artifacts when available; do not relaunch just for completeness.\n- Make Repair/Learn target selection default to declared-hub scope while retaining all 96 in historical knowledge.\n- Domain Refresh: preserve structured CONFIG/source-qualified filenames and recompute activation from final `official_hub`.\n- Reconcile CHANGELOG, VALIDATION metadata, README EN/FR, ARCHITECTURE/VALIDATION wording, `ARCHITECTURE.docx`, and stale Lab trigger counters.\n- Recheck CodeQL/security-extended and `npm audit --omit=dev --audit-level=high` after runtime stabilization.\n- Repository hygiene: remove obsolete one-shots/triggers and prune only truly unreferenced/recoverable artifacts.\n- Revisit audio/player metadata only after identity/extraction correctness is stable.\n'''
    memory.write_text(text.rstrip() + block + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write-scope", action="store_true")
    ap.add_argument("--verify-catalog", action="store_true")
    ap.add_argument("--append-memory", action="store_true")
    args = ap.parse_args()
    scope = compute_scope()
    if args.write_scope:
        write_scope(scope)
    if args.verify_catalog:
        verify_catalog(scope)
    if args.append_memory:
        append_memory(scope)
    print("HUB_ACTIVATION_SCOPE", f"enabled={scope['enabledProviderCount']}", f"disabled={scope['disabledProviderCount']}", ",".join(scope["enabledProviders"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
