#!/usr/bin/env python3
"""Materialize validated clean ProviderBase candidates as review-only proposal artifacts.

This script never publishes or edits the repository's live ProviderBase tree.
It rebuilds deterministic NiakVIO-owned base bytes from the structured clean
model plus the proposed durable overrides, then writes a proposed provenance
file and candidate base files under the requested output directory.

Canonical promotion remains responsible for turning a candidate into a verified
v2 ProviderBase after fresh pipeline proof.
"""
from __future__ import annotations

import argparse
import copy
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from provider_base_store import (
    CLEAN_RECONSTRUCTION_AUTHORING_VERSION,
    CLEAN_RECONSTRUCTION_CANDIDATE_SOURCE,
    base_relative,
    build_base_from_seed,
    build_clean_provider_seed,
    canonical_id,
    sha256,
)

ROOT = Path(__file__).resolve().parents[1]


def load_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path}: expected object")
    return value


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def candidate_map(registry: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {
        canonical_id(str(row.get("canonical_id") or row.get("upstream_id") or "")): row
        for row in registry.get("candidates") or []
        if isinstance(row, dict)
        and canonical_id(str(row.get("canonical_id") or row.get("upstream_id") or ""))
    }


def lab_is_strictly_playable(row: dict[str, Any]) -> bool:
    lab = row.get("finalLab") if isinstance(row.get("finalLab"), dict) else {}
    if row.get("resolved") is not True or lab.get("status") != "playable":
        return False
    if lab.get("allReturnedStreams") is not True:
        return False
    clients = lab.get("clients") if isinstance(lab.get("clients"), dict) else {}
    if not clients:
        return False
    return all(
        isinstance(value, dict)
        and value.get("hiddenFailure") is False
        and value.get("probeCoverageComplete") is True
        and int(value.get("playableProbes") or 0) > 0
        for value in clients.values()
    )



def ensure_proposal_provenance_row(
    rows: dict[str, Any],
    provider_id: str,
    candidate: dict[str, Any],
    origin: str,
    now: str,
) -> dict[str, Any]:
    """Return existing provenance or create a fail-closed row for a new clean seed.

    Published/pending-reconstruction providers must already have provenance.
    Only a genuinely new NiakVIO-owned clean seed may enter Learning proposal
    provenance without a historical row, and that synthesized row is explicitly
    non-publishable/non-activatable until the canonical pipeline proves it.
    """
    current = rows.get(provider_id)
    if isinstance(current, dict):
        return current
    if origin != "new-niakvio-clean-seed":
        raise ValueError(f"{provider_id}: missing provenance row")

    upstream_id = canonical_id(str(candidate.get("upstream_id") or provider_id)) or provider_id
    row: dict[str, Any] = {
        "id": provider_id,
        "published_filename": None,
        "sha256": None,
        "patched_sha256": None,
        "local_patches": [],
        "source": "niakvio-learning-clean-proposal",
        "source_name": "NiakVIO clean reconstruction Learning proposal",
        "source_repository": "NiakVIO",
        "source_license": "GPL-3.0-only",
        "source_license_evidence": "LICENSE",
        "upstream_id": upstream_id,
        "upstream_filename": str(candidate.get("upstream_filename") or "") or None,
        "checked_at": now,
        "check_mode": "brain_learning_clean_proposal",
        "check_status": "pending",
        "health_score": 0,
        "activation_eligible": False,
        "strict_activation_eligible": False,
        "runtime_evidence_eligible": False,
        "activation_mode": "learning_proposal_pending",
        "activation_blockers": ["canonical_pipeline_proof_required"],
        "proposal_only": True,
        "publication_allowed": False,
        "production_writes_allowed": False,
        "candidate_code_origin": origin,
        "upstream_code_role": "knowledge-only",
        "upstream_code_executed": False,
        "legacy_provider_js_executed_for_reconstruction": False,
    }
    rows[provider_id] = row
    return row

def materialize_supporting_bases(
    rows: dict[str, Any],
    output_dir: Path,
    *,
    source_root: Path = ROOT,
) -> list[str]:
    """Make proposed provenance self-contained.

    Learning preflight may rematerialize the canonical current ProviderBase store
    without committing those generated bytes to the exact source SHA. A proposal
    that carries that refreshed provenance must therefore carry every referenced
    base byte as well, not only newly reconstructed candidates.
    """
    copied: list[str] = []
    missing: list[str] = []
    invalid: list[str] = []
    for provider_id, row in sorted(rows.items()):
        if not isinstance(row, dict):
            continue
        relative = str(row.get("base_filename") or "").strip()
        if not relative:
            continue
        rel = Path(relative)
        if (
            not relative.startswith("provider-bases/")
            or rel.is_absolute()
            or ".." in rel.parts
            or rel.name != relative.split("/")[-1]
        ):
            invalid.append(f"{provider_id}:{relative}")
            continue
        expected = str(row.get("base_sha256") or "").strip().casefold()
        target = output_dir / rel.name
        if not target.is_file():
            source = source_root / rel
            if not source.is_file() and expected:
                # Historical provenance may retain a provider-specific path
                # after the identical content-addressed base was archived under
                # another provider/lifecycle tree. Reuse bytes only by exact
                # content hash; provider/path names are never trusted.
                digest_prefix = expected[:16]
                archive_roots = (
                    source_root / "provider-bases",
                    source_root / "provider-disabled" / "provider-bases",
                    source_root / "provider-old" / "provider-bases",
                )
                for archive_root in archive_roots:
                    if not archive_root.is_dir():
                        continue
                    for candidate in archive_root.glob(f"*--base--{digest_prefix}.js"):
                        try:
                            candidate_raw = candidate.read_bytes()
                        except OSError:
                            continue
                        if sha256(candidate_raw).casefold() == expected:
                            source = candidate
                            break
                    if source.is_file():
                        break
            if not source.is_file():
                missing.append(f"{provider_id}:{relative}")
                continue
            shutil.copyfile(source, target)
            copied.append(provider_id)
        raw = target.read_bytes()
        if expected and sha256(raw).casefold() != expected:
            invalid.append(f"{provider_id}:{relative}:sha")
    if missing or invalid:
        raise ValueError(
            "proposal provenance is not self-contained: "
            f"missing={missing[:12]} invalid={invalid[:12]}"
        )
    return copied


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--stage", type=Path, required=True)
    parser.add_argument("--queue-summary", type=Path, required=True)
    parser.add_argument("--overrides", type=Path, required=True)
    parser.add_argument("--provenance", type=Path, default=ROOT / "PROVENANCE.json")
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--proposed-provenance", type=Path, required=True)
    parser.add_argument("--summary", type=Path, required=True)
    args = parser.parse_args()

    registry = load_json(args.stage.resolve())
    queue = load_json(args.queue_summary.resolve())
    provenance = load_json(args.provenance.resolve())
    rows = provenance.get("providers")
    if not isinstance(rows, dict):
        raise ValueError("PROVENANCE.providers must be an object")
    candidates = candidate_map(registry)
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    proposed = copy.deepcopy(provenance)
    proposed_rows = proposed.setdefault("providers", {})
    accepted: list[dict[str, Any]] = []
    rejected: list[dict[str, str]] = []
    now = datetime.now(timezone.utc).isoformat()

    queue_results = {
        canonical_id(str(result.get("provider") or "")): result
        for result in queue.get("results") or []
        if isinstance(result, dict)
        and canonical_id(str(result.get("provider") or ""))
    }

    # Persist every structurally valid NiakVIO-owned clean reconstruction as a
    # durable *candidate*, even when Learning did not reach it or the provider
    # is temporarily unavailable. Runtime proof belongs to the canonical Deep
    # gate; proposal persistence must not throw away clean authoring work.
    for provider_id in sorted(candidates):
        candidate = candidates[provider_id]
        if candidate.get("provider_base_reconstruction_required") is not True:
            continue

        result = queue_results.get(provider_id, {})
        strict_lab_playable = lab_is_strictly_playable(result)

        origin = str(candidate.get("candidate_code_origin") or "")
        if origin not in {
            "new-niakvio-clean-seed",
            "pending-niakvio-clean-reconstruction-v2",
        }:
            rejected.append({"provider": provider_id, "reason": "candidate_not_clean_owned"})
            continue
        if candidate.get("upstream_code_executed") is not False:
            raise ValueError(f"{provider_id}: upstream JS execution flag is not false")
        if candidate.get("legacy_provider_js_executed_for_reconstruction") is not False:
            raise ValueError(f"{provider_id}: legacy JS execution flag is not false")

        metadata = candidate.get("metadata") if isinstance(candidate.get("metadata"), dict) else {}
        model = candidate.get("clean_provider_model") if isinstance(candidate.get("clean_provider_model"), dict) else {}
        seed = build_clean_provider_seed(
            provider_id,
            metadata,
            known_site=str(candidate.get("observed_upstream_site") or "").strip() or None,
            provider_model=model,
        )
        # build_base_from_seed performs the ProviderBase structural/layering
        # validation. A clean candidate that cannot compile still fails closed.
        base_data, stripped = build_base_from_seed(
            provider_id,
            seed,
            overrides_path=args.overrides.resolve(),
        )
        digest = sha256(base_data)
        relative = base_relative(provider_id, digest)
        target = output_dir / Path(relative).name
        target.write_bytes(base_data)

        current = ensure_proposal_provenance_row(
            proposed_rows,
            provider_id,
            candidate,
            origin,
            now,
        )
        if str(current.get("base_source") or "") != CLEAN_RECONSTRUCTION_CANDIDATE_SOURCE:
            current.setdefault("legacy_base_filename_before_clean_candidate", current.get("base_filename"))
            current.setdefault("legacy_base_sha256_before_clean_candidate", current.get("base_sha256"))
            current.setdefault("legacy_base_source_before_clean_candidate", current.get("base_source"))
        current["base_filename"] = relative
        current["base_sha256"] = digest
        current["base_source"] = CLEAN_RECONSTRUCTION_CANDIDATE_SOURCE
        current["clean_reconstruction_candidate"] = True
        current["clean_reconstruction_verified"] = False
        current["clean_reconstruction_required"] = True
        current["clean_reconstruction_authoring_version"] = CLEAN_RECONSTRUCTION_AUTHORING_VERSION
        current["clean_reconstruction_candidate_at"] = now
        current["clean_reconstruction_candidate_origin"] = origin
        current["clean_reconstruction_candidate_lab"] = (
            "tv-desktop-mobile-complete-playable"
            if strict_lab_playable
            else "canonical-deep-proof-pending"
        )
        current["clean_reconstruction_candidate_learning_strict_playable"] = strict_lab_playable
        current["legacy_provider_js_executed_for_reconstruction"] = False
        current["upstream_code_role"] = "knowledge-only"
        current["upstream_code_executed"] = False
        current["base_migration_stripped_generated_core"] = bool(stripped)
        accepted.append({
            "provider": provider_id,
            "base_filename": relative,
            "base_sha256": digest,
            "source": CLEAN_RECONSTRUCTION_CANDIDATE_SOURCE,
            "learning_strict_playable": strict_lab_playable,
        })

    store = proposed.setdefault("provider_base_store", {})
    if isinstance(store, dict):
        store.update({
            "schema_version": max(5, int(store.get("schema_version") or 0)),
            "clean_candidate_count_this_proposal": len(accepted),
            "clean_candidate_policy": "review-only-until-canonical-pipeline-proof",
            "clean_candidate_generated_at": now,
            "upstream_code_role": "knowledge-only",
            "upstream_code_executed": False,
        })

    strict_lab_playable_count = sum(
        1 for row in accepted if row.get("learning_strict_playable") is True
    )
    strict_lab_pending_count = len(accepted) - strict_lab_playable_count
    supporting = materialize_supporting_bases(proposed_rows, output_dir)

    write_json(args.proposed_provenance.resolve(), proposed)
    write_json(args.summary.resolve(), {
        "schemaVersion": 2,
        "generatedAt": now,
        "candidateCount": len(accepted),
        "strictLabPlayableCount": strict_lab_playable_count,
        "strictLabPendingCount": strict_lab_pending_count,
        "supportingBaseCount": len(supporting),
        "supportingBaseProviders": supporting,
        "providers": [row["provider"] for row in accepted],
        "candidates": accepted,
        "rejected": rejected,
        "policy": {
            "publicationAllowed": False,
            "productionWritesAllowed": False,
            "pullRequestOnly": True,
            "requiresHumanMerge": True,
            "canonicalPipelineProofRequired": True,
            "strictLearningProofRequiredForProposal": False,
            "strictDeepProofRequiredForVerification": True,
            "legacyOrUpstreamExecutableSeedAllowed": False,
        },
    })
    print(
        "FIELD_CLEAN_PROVIDER_PROPOSAL "
        f"candidates={len(accepted)} strict_lab_playable={strict_lab_playable_count} "
        f"strict_lab_pending={strict_lab_pending_count} supporting_bases={len(supporting)} rejected={len(rejected)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
