#!/usr/bin/env python3
"""Render a durable one-row-per-provider Markdown table from a full provider census."""
from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

GOOD = "playable_verified"


def load(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(path)
    return value


def lane_ok(row: dict[str, Any]) -> bool:
    return (
        str(row.get("status") or "") == GOOD
        and int(row.get("verified") or 0) > 0
        and int(row.get("contradictions") or 0) == 0
    )


def provider_state(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return "ZERO"
    good = sum(1 for row in rows if lane_ok(row))
    if good == len(rows):
        return "FULL"
    if good:
        return "PARTIAL"
    return "ZERO"


def dominant_issue(rows: list[dict[str, Any]]) -> str:
    failed = [row for row in rows if not lane_ok(row)]
    if not failed:
        return "none"
    counts = Counter(str(row.get("debug_stage") or row.get("status") or "unknown") for row in failed)
    return ", ".join(
        stage if count == 1 else f"{stage}×{count}"
        for stage, count in counts.most_common(3)
    )


def render(report: dict[str, Any], *, run_id: str, sha: str) -> str:
    by: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in report.get("rows") or []:
        if not isinstance(row, dict):
            continue
        provider = str(row.get("provider_id") or "").strip().casefold()
        if provider:
            by[provider].append(row)

    expected = int(report.get("provider_count") or len(by))
    if len(by) != expected:
        raise ValueError(f"census provider mismatch: expected={expected} actual={len(by)}")

    states = Counter(provider_state(rows) for rows in by.values())
    short_sha = sha[:12] if sha else "unknown"
    lines = [
        "# Provider Census Status",
        "",
        "> Auto-generated by `scripts/render_provider_census_status.py`. Do not edit the table manually.",
        "",
        f"Latest full census: **{states.get('FULL', 0)} FULL / {states.get('PARTIAL', 0)} PARTIAL / {states.get('ZERO', 0)} ZERO** across **{len(by)} providers**.",
        f"Evidence: run `{run_id or 'local'}` · SHA `{short_sha}`.",
        "",
        "`FULL` = every declared semantic lane returned identity-verified playable output. "
        "`PARTIAL` = at least one declared lane did. `ZERO` = none did. "
        "Historical route qualification does not count as terminal playback proof.",
        "",
        "| Provider | State | Declared lanes | Verified lanes | Latest lane verdicts | Dominant issue |",
        "|---|---:|---|---|---|---|",
    ]

    state_order = {"PARTIAL": 0, "ZERO": 1, "FULL": 2}
    entries = []
    for provider, rows in by.items():
        ordered = sorted(rows, key=lambda row: str(row.get("semantic_type") or ""))
        state = provider_state(ordered)
        declared = [str(row.get("semantic_type") or "") for row in ordered]
        verified = [str(row.get("semantic_type") or "") for row in ordered if lane_ok(row)]
        verdicts = []
        for row in ordered:
            lane = str(row.get("semantic_type") or "")
            status = str(row.get("status") or "unknown")
            stage = str(row.get("debug_stage") or "")
            if lane_ok(row):
                verdicts.append(f"{lane}=OK")
            else:
                verdicts.append(f"{lane}={status}" + (f"/{stage}" if stage and stage != status else ""))
        entries.append((
            state_order.get(state, 9),
            provider,
            f"| `{provider}` | **{state}** | {', '.join(declared) or '—'} | "
            f"{', '.join(verified) or '—'} | {'; '.join(verdicts) or '—'} | "
            f"`{dominant_issue(ordered)}` |",
        ))

    lines.extend(row for _, _, row in sorted(entries))
    lines.extend([
        "",
        "The source JSON for this table is the exact `provider-v3-quick-yield.json` produced by the same census run.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("report", type=Path)
    parser.add_argument("--output", type=Path, default=Path("PROVIDER_CENSUS_STATUS.md"))
    parser.add_argument("--run-id", default="")
    parser.add_argument("--sha", default="")
    args = parser.parse_args()
    report = load(args.report)
    args.output.write_text(render(report, run_id=str(args.run_id), sha=str(args.sha)), encoding="utf-8")
    print(f"PROVIDER_CENSUS_STATUS_WRITTEN output={args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
